_BASE_: "Base-KepSalinst-R50.yaml"
INPUT:
  MAX_SIZE_TRAIN: 480
  MIN_SIZE_TRAIN: (320, )
  MAX_SIZE_TEST: 480
  MIN_SIZE_TEST: 320
DATASETS:
  TRAIN: ("ILSO1K_trainval",)
  TEST: ("ILSO1K_test",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 1000
  STEPS: (1531, ) # ~ 35 epoches
  MAX_ITER: 1750 # ~ 40 epoches
  CHECKPOINT_PERIOD: 500
OUTPUT_DIR: "output/KepSalinst/ILSO1K"
