_BASE_: "Base-KepSalinst-R50.yaml"
INPUT:
  MAX_SIZE_TRAIN: 480
  MIN_SIZE_TRAIN: (320, )
  MAX_SIZE_TEST: 480
  MIN_SIZE_TEST: 320
DATASETS:
  TRAIN: ("SIS10K_train",)
  TEST: ("SIS10K_test",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 1000
  STEPS: (5273, ) # ~ 12 epoches
  MAX_ITER: 6151 # ~ 14 epoches
  CHECKPOINT_PERIOD: 1000
OUTPUT_DIR: "output/KepSalinst/SIS10K"

